<?php
if (session_status() === PHP_SESSION_NONE) {
    session_start();
}

$availableLanguages = ["es", "en", "pt", "it"];

if (isset($_GET["lang"]) && in_array($_GET["lang"], $availableLanguages, true)) {
    $_SESSION["lang"] = $_GET["lang"];
}

$currentLang = $_SESSION["lang"] ?? "es";

$translations = [
    "es" => [
        "Inicio" => "Inicio",
        "Nosotros" => "Nosotros",
        "Habitaciones" => "Habitaciones",
        "Servicios" => "Servicios",
        "Normas" => "Normas",
        "Galería" => "Galería",
        "Reseñas" => "Reseñas",
        "Contacto" => "Contacto",
        "Mi Cuenta" => "Mi Cuenta",
        "Mis Reservas" => "Mis Reservas",
        "Mis Reclamos" => "Mis Reclamos",
        "Hola" => "Hola",
        "Salir" => "Salir",
        "Iniciar sesión" => "Iniciar sesión",
        "Iniciar sesi&oacute;n" => "Iniciar sesi&oacute;n",
    ],
    "en" => [
            "Inicio" => "Home",
            "Galer&iacute;a" => "Gallery",
            "Rese&ntilde;as" => "Reviews",
            "Cambiar contrase&ntilde;a" => "Change Password",
            "Nosotros" => "About Us",
        "Habitaciones" => "Rooms",
        "Servicios" => "Services",
        "Normas" => "Rules",
        "Galería" => "Gallery",
        "Reseñas" => "Reviews",
        "Contacto" => "Contact",
        "Mi Cuenta" => "My Account",
        "Mis Reservas" => "My Bookings",
        "Mis Reclamos" => "My Complaints",
        "Hola" => "Hello",
        "Salir" => "Log out",
        "Iniciar sesión" => "Sign in",
        "Iniciar sesi&oacute;n" => "Sign in",
    ],
    "pt" => [
            "Inicio" => "Início",
            "Galer&iacute;a" => "Galeria",
            "Rese&ntilde;as" => "Avaliações",
            "Cambiar contrase&ntilde;a" => "Alterar senha",
            "Nosotros" => "Sobre nós",
        "Habitaciones" => "Quartos",
        "Servicios" => "Serviços",
        "Normas" => "Regras",
        "Galería" => "Galeria",
        "Reseñas" => "Avaliações",
        "Contacto" => "Contato",
        "Mi Cuenta" => "Minha Conta",
        "Mis Reservas" => "Minhas Reservas",
        "Mis Reclamos" => "Minhas Reclamações",
        "Hola" => "Olá",
        "Salir" => "Sair",
        "Iniciar sesión" => "Entrar",
        "Iniciar sesi&oacute;n" => "Entrar",
    ],
    "it" => [
            "Inicio" => "Home",
            "Galer&iacute;a" => "Galleria",
            "Rese&ntilde;as" => "Recensioni",
            "Cambiar contrase&ntilde;a" => "Cambia password",
            "Nosotros" => "Chi siamo",
        "Habitaciones" => "Camere",
        "Servicios" => "Servizi",
        "Normas" => "Regole",
        "Galería" => "Galleria",
        "Reseñas" => "Recensioni",
        "Contacto" => "Contatto",
        "Mi Cuenta" => "Il mio account",
        "Mis Reservas" => "Le mie prenotazioni",
        "Mis Reclamos" => "I miei reclami",
        "Hola" => "Ciao",
        "Salir" => "Esci",
        "Iniciar sesión" => "Accedi",
        "Iniciar sesi&oacute;n" => "Accedi",
    ],
];

function t($key)
{
    global $translations, $currentLang;
    return $translations[$currentLang][$key] ?? $translations["es"][$key] ?? $key;
}

function languageUrl($lang)
{
    $params = $_GET;
    $params["lang"] = $lang;
    $query = http_build_query($params);
    $script = $_SERVER["PHP_SELF"] ?? "";
    return htmlspecialchars($script . ($query ? "?" . $query : ""));
}

function repairSpanishText($html)
{
    $replacements = [
        "Ã¡" => "á", "Ã©" => "é", "Ã­" => "í", "Ã³" => "ó", "Ãº" => "ú",
        "Ã" => "Á", "Ã‰" => "É", "Ã" => "Í", "Ã“" => "Ó", "Ãš" => "Ú",
        "Ã±" => "ñ", "Ã‘" => "Ñ", "Ã¼" => "ü", "Â¿" => "¿", "Â¡" => "¡",
        "Âº" => "º", "Âª" => "ª", "Â·" => "·", "Â " => " ",
        "âœ“" => "✓", "â†’" => "→", "â€“" => "-", "â€”" => "-",
        "ðŸ’³" => "💳", "ðŸ“±" => "📱", "ðŸ¦" => "🏦",
        "GalerÃ­a" => "Galería", "ReseÃ±as" => "Reseñas",
        "HabitaciÃ³n" => "Habitación", "habitaciÃ³n" => "habitación",
        "Reservar HabitaciÃ³n" => "Reservar Habitación",
        "MÃ©todo" => "Método", "InformaciÃ³n" => "Información",
        "TelÃ©fono" => "Teléfono", "PaÃ­s" => "País", "NiÃ±os" => "Niños",
        "HuÃ©spedes" => "Huéspedes", "ContraseÃ±a" => "Contraseña",
        "contraseÃ±a" => "contraseña", "UbicaciÃ³n" => "Ubicación",
        "PolÃ­tica" => "Política", "AtenciÃ³n" => "Atención",
        "electrÃ³nicos" => "electrónicos", "ContÃ¡ctanos" => "Contáctanos",
        "dÃ­as" => "días", "PerÃº" => "Perú", "Tacna - PerÃº" => "Tacna - Perú",
    ];

    return strtr($html, $replacements);
}

function publicTranslationMap($lang)
{
    $maps = [
        "en" => [
            "BIENVENIDO A" => "WELCOME TO",
            "TU HOGAR EN TACNA" => "YOUR HOME IN TACNA",
            "Tu hogar en Tacna" => "Your home in Tacna",
            "Vive una experiencia única con habitaciones cómodas, atención personalizada y el mejor servicio para hacer de tu estadía un momento inolvidable." => "Enjoy a unique experience with comfortable rooms, personalized service and the best attention to make your stay unforgettable.",
            "Reservar Ahora" => "Book Now",
            "Conócenos" => "About Us",
            "Habitaciones Destacadas" => "Featured Rooms",
            "Descubre nuestras habitaciones más solicitadas." => "Discover our most requested rooms.",
            "Reservar Habitación" => "Book a Room",
            "Reservar" => "Book",
            "Ver Detalles" => "View Details",
            "VER DETALLES" => "VIEW DETAILS",
            "Ver historial" => "View history",
            "Volver" => "Back",
            "Continuar" => "Continue",
            "Anterior" => "Previous",
            "Confirmar Reserva" => "Confirm Booking",
            "Detalles de tu Reserva" => "Your Booking Details",
            "Información Personal" => "Personal Information",
            "Método de Pago" => "Payment Method",
            "Instrucciones de Pago" => "Payment Instructions",
            "Resumen de Reserva" => "Booking Summary",
            "Resumen Final" => "Final Summary",
            "Total a Pagar" => "Total to Pay",
            "Fecha de Entrada" => "Check-in Date",
            "Fecha de Salida" => "Check-out Date",
            "Tipo de Habitación" => "Room Type",
            "Adultos" => "Adults",
            "Niños" => "Children",
            "Noches" => "Nights",
            "Huéspedes" => "Guests",
            "Nombre" => "First name",
            "Apellido" => "Last name",
            "Correo" => "Email",
            "Correo electrónico" => "Email",
            "Teléfono" => "Phone",
            "País de Procedencia" => "Country of Origin",
            "Ciudad" => "City",
            "Habitación" => "Room",
            "habitaciones" => "rooms",
            "personas" => "people",
            "noche" => "night",
            "Selecciona un método de pago para ver las instrucciones." => "Select a payment method to see the instructions.",
            "Transferencia Bancaria" => "Bank Transfer",
            "Central de reservas:" => "Booking center:",
            "Medios de pago" => "Payment methods",
            "Reservas" => "Bookings",
            "Atención al cliente" => "Customer Service",
            "Libro de reclamaciones" => "Complaints Book",
            "Preguntas frecuentes" => "Frequently Asked Questions",
            "Política de privacidad" => "Privacy Policy",
            "Comprobantes electrónicos" => "Electronic Receipts",
            "Enlaces de interés" => "Useful Links",
            "Contáctanos" => "Contact Us",
            "Atención 24 horas" => "24-hour service",
            "Todos los días" => "Every day",
            "Todos los derechos reservados - Madison Suite" => "All rights reserved - Madison Suite",
            "Mi Cuenta" => "My Account",
            "Panel de cuenta" => "Account Dashboard",
            "Mi perfil" => "My Profile",
            "Mi Perfil" => "My Profile",
            "Historial" => "History",
            "Cambiar contraseña" => "Change Password",
            "Mis Reservas" => "My Bookings",
            "Mis Reclamos" => "My Complaints",
            "Bienvenido" => "Welcome",
            "Desde aquí puedes revisar tus reservas, reclamos y datos personales." => "From here you can review your bookings, complaints and personal data.",
            "Consulta tus reservas actuales." => "Check your current bookings.",
            "Consulta el estado de tus reclamos." => "Check the status of your complaints.",
            "Consulta tus datos personales." => "Check your personal information.",
            "Actualiza tu contraseña de acceso." => "Update your access password.",
            "Contraseña" => "Password",
            "Nueva contraseña" => "New password",
            "Confirmar contraseña" => "Confirm password",
            "Actualizar contraseña" => "Update password",
            "Libro de Reclamaciones Virtual" => "Virtual Complaints Book",
            "Enviar Reclamación" => "Submit Complaint",
            "Identificación del Consumidor" => "Consumer Identification",
            "Identificación del Bien Contratado" => "Purchased Service Identification",
            "Detalle de la Reclamación" => "Complaint Details",
            "Nombre completo" => "Full name",
            "Documento de identidad" => "Identity document",
            "Domicilio" => "Address",
            "Tipo de bien" => "Type of item",
            "Servicio" => "Service",
            "Producto" => "Product",
            "Monto reclamado" => "Claimed amount",
            "Descripción del bien o servicio" => "Description of item or service",
            "Tipo de incidencia" => "Incident type",
            "Queja" => "Grievance",
            "Reclamo" => "Complaint",
            "Detalle del reclamo o queja" => "Complaint or grievance detail",
            "Pedido del consumidor" => "Consumer request",
            "Nuevo Reclamo" => "New Complaint",
            "Estado" => "Status",
            "Pendiente" => "Pending",
            "Confirmada" => "Confirmed",
            "Cancelada" => "Cancelled",
            "Atendida" => "Resolved",
            "Página no encontrada" => "Page Not Found",
            "ERROR 404" => "ERROR 404",
            "Oh no, algo ha salido mal." => "Oh no, something went wrong.",
            "Parece que la página que estás buscando no existe o ha sido movida." => "The page you are looking for does not exist or has been moved.",
            "Volver a la Página de Inicio" => "Back to Home Page",
            "¿Puedo ayudarte a encontrar algo más?" => "Can I help you find something else?",
            "Ver Nuestras Habitaciones" => "View Our Rooms",
            "Contactar al Hotel" => "Contact the Hotel",
            "Preguntas Frecuentes - Madison Suite" => "Frequently Asked Questions - Madison Suite",
            "Hora y Entrada" => "Check-in and Time",
            "Amenidades y Servicios" => "Amenities and Services",
            "Ubicación y Precios" => "Location and Prices",
            "¿Sigues buscando?" => "Still looking?",
            "Hacer una pregunta" => "Ask a question",
        ],
        "pt" => [
            "BIENVENIDO A" => "BEM-VINDO AO",
            "TU HOGAR EN TACNA" => "SEU LAR EM TACNA",
            "Tu hogar en Tacna" => "Seu lar em Tacna",
            "Vive una experiencia única con habitaciones cómodas, atención personalizada y el mejor servicio para hacer de tu estadía un momento inolvidable." => "Viva uma experiência única com quartos confortáveis, atendimento personalizado e o melhor serviço para tornar sua estadia inesquecível.",
            "Reservar Ahora" => "Reservar Agora",
            "Conócenos" => "Conheça-nos",
            "Habitaciones Destacadas" => "Quartos em Destaque",
            "Descubre nuestras habitaciones más solicitadas." => "Conheça nossos quartos mais solicitados.",
            "Reservar Habitación" => "Reservar Quarto",
            "Reservar" => "Reservar",
            "Ver Detalles" => "Ver Detalhes",
            "VER DETALLES" => "VER DETALHES",
            "Ver historial" => "Ver histórico",
            "Volver" => "Voltar",
            "Continuar" => "Continuar",
            "Anterior" => "Anterior",
            "Confirmar Reserva" => "Confirmar Reserva",
            "Detalles de tu Reserva" => "Detalhes da sua Reserva",
            "Información Personal" => "Informações Pessoais",
            "Método de Pago" => "Método de Pagamento",
            "Instrucciones de Pago" => "Instruções de Pagamento",
            "Resumen de Reserva" => "Resumo da Reserva",
            "Resumen Final" => "Resumo Final",
            "Total a Pagar" => "Total a Pagar",
            "Fecha de Entrada" => "Data de Entrada",
            "Fecha de Salida" => "Data de Saída",
            "Tipo de Habitación" => "Tipo de Quarto",
            "Adultos" => "Adultos",
            "Niños" => "Crianças",
            "Noches" => "Noites",
            "Huéspedes" => "Hóspedes",
            "Nombre" => "Nome",
            "Apellido" => "Sobrenome",
            "Correo" => "E-mail",
            "Correo electrónico" => "E-mail",
            "Teléfono" => "Telefone",
            "País de Procedencia" => "País de Origem",
            "Ciudad" => "Cidade",
            "Habitación" => "Quarto",
            "habitaciones" => "quartos",
            "personas" => "pessoas",
            "noche" => "noite",
            "Selecciona un método de pago para ver las instrucciones." => "Selecione um método de pagamento para ver as instruções.",
            "Transferencia Bancaria" => "Transferência Bancária",
            "Central de reservas:" => "Central de reservas:",
            "Medios de pago" => "Meios de pagamento",
            "Reservas" => "Reservas",
            "Atención al cliente" => "Atendimento ao Cliente",
            "Libro de reclamaciones" => "Livro de Reclamações",
            "Preguntas frecuentes" => "Perguntas Frequentes",
            "Política de privacidad" => "Política de Privacidade",
            "Comprobantes electrónicos" => "Comprovantes Eletrônicos",
            "Enlaces de interés" => "Links Úteis",
            "Contáctanos" => "Fale Conosco",
            "Atención 24 horas" => "Atendimento 24 horas",
            "Todos los días" => "Todos os dias",
            "Todos los derechos reservados - Madison Suite" => "Todos os direitos reservados - Madison Suite",
            "Mi Cuenta" => "Minha Conta",
            "Panel de cuenta" => "Painel da conta",
            "Mi perfil" => "Meu perfil",
            "Mi Perfil" => "Meu Perfil",
            "Historial" => "Histórico",
            "Cambiar contraseña" => "Alterar senha",
            "Mis Reservas" => "Minhas Reservas",
            "Mis Reclamos" => "Minhas Reclamações",
            "Bienvenido" => "Bem-vindo",
            "Desde aquí puedes revisar tus reservas, reclamos y datos personales." => "Aqui você pode revisar suas reservas, reclamações e dados pessoais.",
            "Consulta tus reservas actuales." => "Consulte suas reservas atuais.",
            "Consulta el estado de tus reclamos." => "Consulte o estado das suas reclamações.",
            "Consulta tus datos personales." => "Consulte seus dados pessoais.",
            "Actualiza tu contraseña de acceso." => "Atualize sua senha de acesso.",
            "Contraseña" => "Senha",
            "Nueva contraseña" => "Nova senha",
            "Confirmar contraseña" => "Confirmar senha",
            "Actualizar contraseña" => "Atualizar senha",
            "Libro de Reclamaciones Virtual" => "Livro de Reclamações Virtual",
            "Enviar Reclamación" => "Enviar Reclamação",
            "Identificación del Consumidor" => "Identificação do Consumidor",
            "Identificación del Bien Contratado" => "Identificação do Serviço Contratado",
            "Detalle de la Reclamación" => "Detalhe da Reclamação",
            "Nombre completo" => "Nome completo",
            "Documento de identidad" => "Documento de identidade",
            "Domicilio" => "Endereço",
            "Tipo de bien" => "Tipo de item",
            "Servicio" => "Serviço",
            "Producto" => "Produto",
            "Monto reclamado" => "Valor reclamado",
            "Descripción del bien o servicio" => "Descrição do item ou serviço",
            "Tipo de incidencia" => "Tipo de ocorrência",
            "Queja" => "Queixa",
            "Reclamo" => "Reclamação",
            "Detalle del reclamo o queja" => "Detalhe da reclamação ou queixa",
            "Pedido del consumidor" => "Pedido do consumidor",
            "Nuevo Reclamo" => "Nova Reclamação",
            "Estado" => "Estado",
            "Pendiente" => "Pendente",
            "Confirmada" => "Confirmada",
            "Cancelada" => "Cancelada",
            "Atendida" => "Resolvida",
            "Página no encontrada" => "Página não encontrada",
            "ERROR 404" => "ERRO 404",
            "Oh no, algo ha salido mal." => "Oh não, algo deu errado.",
            "Parece que la página que estás buscando no existe o ha sido movida." => "A página que você procura não existe ou foi movida.",
            "Volver a la Página de Inicio" => "Voltar à Página Inicial",
            "¿Puedo ayudarte a encontrar algo más?" => "Posso ajudar você a encontrar algo mais?",
            "Ver Nuestras Habitaciones" => "Ver Nossos Quartos",
            "Contactar al Hotel" => "Contatar o Hotel",
            "Preguntas Frecuentes - Madison Suite" => "Perguntas Frequentes - Madison Suite",
            "Hora y Entrada" => "Horário e Entrada",
            "Amenidades y Servicios" => "Comodidades e Serviços",
            "Ubicación y Precios" => "Localização e Preços",
            "¿Sigues buscando?" => "Ainda procurando?",
            "Hacer una pregunta" => "Fazer uma pergunta",
        ],
        "it" => [
            "BIENVENIDO A" => "BENVENUTO A",
            "TU HOGAR EN TACNA" => "LA TUA CASA A TACNA",
            "Tu hogar en Tacna" => "La tua casa a Tacna",
            "Vive una experiencia única con habitaciones cómodas, atención personalizada y el mejor servicio para hacer de tu estadía un momento inolvidable." => "Vivi un'esperienza unica con camere confortevoli, attenzione personalizzata e il miglior servizio per rendere il tuo soggiorno indimenticabile.",
            "Reservar Ahora" => "Prenota Ora",
            "Conócenos" => "Scoprìci",
            "Habitaciones Destacadas" => "Camere in Evidenza",
            "Descubre nuestras habitaciones más solicitadas." => "Scopri le nostre camere più richieste.",
            "Reservar Habitación" => "Prenota Camera",
            "Reservar" => "Prenota",
            "Ver Detalles" => "Vedi Dettagli",
            "VER DETALLES" => "VEDI DETTAGLI",
            "Ver historial" => "Vedi storico",
            "Volver" => "Indietro",
            "Continuar" => "Continua",
            "Anterior" => "Precedente",
            "Confirmar Reserva" => "Conferma Prenotazione",
            "Detalles de tu Reserva" => "Dettagli della tua Prenotazione",
            "Información Personal" => "Informazioni Personali",
            "Método de Pago" => "Metodo di Pagamento",
            "Instrucciones de Pago" => "Istruzioni di Pagamento",
            "Resumen de Reserva" => "Riepilogo Prenotazione",
            "Resumen Final" => "Riepilogo Finale",
            "Total a Pagar" => "Totale da Pagare",
            "Fecha de Entrada" => "Data di Arrivo",
            "Fecha de Salida" => "Data di Partenza",
            "Tipo de Habitación" => "Tipo di Camera",
            "Adultos" => "Adulti",
            "Niños" => "Bambini",
            "Noches" => "Notti",
            "Huéspedes" => "Ospiti",
            "Nombre" => "Nome",
            "Apellido" => "Cognome",
            "Correo" => "E-mail",
            "Correo electrónico" => "E-mail",
            "Teléfono" => "Telefono",
            "País de Procedencia" => "Paese di Provenienza",
            "Ciudad" => "Città",
            "Habitación" => "Camera",
            "habitaciones" => "camere",
            "personas" => "persone",
            "noche" => "notte",
            "Selecciona un método de pago para ver las instrucciones." => "Seleziona un metodo di pagamento per vedere le istruzioni.",
            "Transferencia Bancaria" => "Bonifico Bancario",
            "Central de reservas:" => "Centro prenotazioni:",
            "Medios de pago" => "Metodi di pagamento",
            "Reservas" => "Prenotazioni",
            "Atención al cliente" => "Servizio Clienti",
            "Libro de reclamaciones" => "Registro Reclami",
            "Preguntas frecuentes" => "Domande Frequenti",
            "Política de privacidad" => "Informativa sulla Privacy",
            "Comprobantes electrónicos" => "Ricevute Elettroniche",
            "Enlaces de interés" => "Link Utili",
            "Contáctanos" => "Contattaci",
            "Atención 24 horas" => "Assistenza 24 ore",
            "Todos los días" => "Tutti i giorni",
            "Todos los derechos reservados - Madison Suite" => "Tutti i diritti riservati - Madison Suite",
            "Mi Cuenta" => "Il mio account",
            "Panel de cuenta" => "Pannello account",
            "Mi perfil" => "Il mio profilo",
            "Mi Perfil" => "Il Mio Profilo",
            "Historial" => "Storico",
            "Cambiar contraseña" => "Cambia password",
            "Mis Reservas" => "Le mie prenotazioni",
            "Mis Reclamos" => "I miei reclami",
            "Bienvenido" => "Benvenuto",
            "Desde aquí puedes revisar tus reservas, reclamos y datos personales." => "Da qui puoi controllare prenotazioni, reclami e dati personali.",
            "Consulta tus reservas actuales." => "Consulta le tue prenotazioni attuali.",
            "Consulta el estado de tus reclamos." => "Consulta lo stato dei tuoi reclami.",
            "Consulta tus datos personales." => "Consulta i tuoi dati personali.",
            "Actualiza tu contraseña de acceso." => "Aggiorna la tua password di accesso.",
            "Contraseña" => "Password",
            "Nueva contraseña" => "Nuova password",
            "Confirmar contraseña" => "Conferma password",
            "Actualizar contraseña" => "Aggiorna password",
            "Libro de Reclamaciones Virtual" => "Registro Reclami Virtuale",
            "Enviar Reclamación" => "Invia Reclamo",
            "Identificación del Consumidor" => "Identificazione del Consumatore",
            "Identificación del Bien Contratado" => "Identificazione del Servizio Contrattato",
            "Detalle de la Reclamación" => "Dettaglio del Reclamo",
            "Nombre completo" => "Nome completo",
            "Documento de identidad" => "Documento d'identità",
            "Domicilio" => "Indirizzo",
            "Tipo de bien" => "Tipo di bene",
            "Servicio" => "Servizio",
            "Producto" => "Prodotto",
            "Monto reclamado" => "Importo reclamato",
            "Descripción del bien o servicio" => "Descrizione del bene o servizio",
            "Tipo de incidencia" => "Tipo di segnalazione",
            "Queja" => "Lamentela",
            "Reclamo" => "Reclamo",
            "Detalle del reclamo o queja" => "Dettaglio del reclamo o lamentela",
            "Pedido del consumidor" => "Richiesta del consumatore",
            "Nuevo Reclamo" => "Nuovo Reclamo",
            "Estado" => "Stato",
            "Pendiente" => "In sospeso",
            "Confirmada" => "Confermata",
            "Cancelada" => "Cancellata",
            "Atendida" => "Risolta",
            "Página no encontrada" => "Pagina non trovata",
            "ERROR 404" => "ERRORE 404",
            "Oh no, algo ha salido mal." => "Oh no, qualcosa è andato storto.",
            "Parece que la página que estás buscando no existe o ha sido movida." => "La pagina che stai cercando non esiste o è stata spostata.",
            "Volver a la Página de Inicio" => "Torna alla Home",
            "¿Puedo ayudarte a encontrar algo más?" => "Posso aiutarti a trovare qualcos'altro?",
            "Ver Nuestras Habitaciones" => "Vedi le Nostre Camere",
            "Contactar al Hotel" => "Contatta l'Hotel",
            "Preguntas Frecuentes - Madison Suite" => "Domande Frequenti - Madison Suite",
            "Hora y Entrada" => "Orario e Ingresso",
            "Amenidades y Servicios" => "Comfort e Servizi",
            "Ubicación y Precios" => "Posizione e Prezzi",
            "¿Sigues buscando?" => "Stai ancora cercando?",
            "Hacer una pregunta" => "Fai una domanda",
        ],
    ];

    return $maps[$lang] ?? [];
}

function publicTranslationOverrides($lang)
{
    $maps = [
        "en" => [
            "Nosotros" => "About Us",
            "Servicios" => "Services",
            "Normas" => "Rules",
            "Galería" => "Gallery",
            "Reseñas" => "Reviews",
            "Contacto" => "Contact",
            "Inicio" => "Home",
            "Habitaciones" => "Rooms",
            "Ubicación" => "Location",
            "Elegancia y descanso" => "Elegance and Rest",
            "Encuentra el espacio perfecto para tu estadía en Tacna." => "Find the perfect space for your stay in Tacna.",
            "Habitación Triple" => "Triple Room",
            "Habitación Matrimonial" => "Matrimonial Room",
            "Habitación Doble" => "Double Room",
            "Habitación Familiar - 3p" => "Family Room - 3p",
            "Familiar Plus - 4p" => "Family Plus - 4p",
            "Suite Familiar - 3p" => "Family Suite - 3p",
            "Suite Executive" => "Executive Suite",
            "Habitación cómoda para tres personas, con cama doble, aire acondicionado y TV." => "Comfortable room for three guests, with a double bed, air conditioning and TV.",
            "Habitación ideal para parejas, con cama matrimonial o dos camas, baño privado y TV cable." => "Ideal room for couples, with one matrimonial bed or two beds, private bathroom and cable TV.",
            "Habitación ideal para parejas, con cama doble, aire acondicionado y TV." => "Ideal room for couples, with a double bed, air conditioning and TV.",
            "Suite amplia con cama doble extragrande, bañera de hidromasaje y sala de estar." => "Spacious suite with an extra-large double bed, whirlpool bathtub and living area.",
            "Suite familiar con cama doble extragrande, bañera de hidromasaje y sala de estar." => "Family suite with an extra-large double bed, whirlpool bathtub and living area.",
            "Habitación familiar con cama individual y cama doble, espacio amplio y artículos de baño." => "Family room with one single bed and one double bed, spacious area and bathroom amenities.",
            "Habitación familiar para cuatro personas, con dos camas individuales y una cama doble." => "Family room for four guests, with two single beds and one double bed.",
            "1 cama doble" => "1 double bed",
            "1 cama matrimonial o 2 camas" => "1 matrimonial bed or 2 beds",
            "1 cama doble extragrande" => "1 extra-large double bed",
            "1 cama individual y 1 cama doble" => "1 single bed and 1 double bed",
            "2 camas individuales y 1 cama doble" => "2 single beds and 1 double bed",
            "Aire Acondicionado" => "Air Conditioning",
            "Baño privado y TV cable" => "Private bathroom and cable TV",
            "Bañera de hidromasaje / Jacuzzi" => "Whirlpool bathtub / Jacuzzi",
            "Escritorio de trabajo" => "Work desk",
            "Sala de estar" => "Living area",
            "Espacio amplio para familias" => "Spacious area for families",
            "Armario y artículos de baño" => "Wardrobe and bathroom amenities",
            "Agua caliente" => "Hot water",
            "Vive una experiencia única con habitaciones cómodas, atención personalizada y el mejor servicio para hacer de tu estadía un momento inolvidable." => "Enjoy a unique experience with comfortable rooms, personalized service and the best attention to make your stay unforgettable.",
            "Seguridad 24/7" => "24/7 Security",
            "Personal capacitado las 24 horas." => "Trained staff available 24 hours a day.",
            "Limpieza" => "Cleanliness",
            "Habitaciones impecables." => "Spotless rooms.",
            "Confort" => "Comfort",
            "Ambientes modernos y acogedores." => "Modern and welcoming spaces.",
            "7 años" => "7 years",
            "Brindando la mejor experiencia." => "Providing the best experience.",
            "¿Por qué elegir Madison Suite?" => "Why choose Madison Suite?",
            "Nos enfocamos en ofrecer una experiencia cómoda y segura para cada huésped. Contamos con habitaciones equipadas, wifi gratuito, atención personalizada, ambientes modernos y una excelente ubicación en la ciudad de Tacna." => "We focus on offering a comfortable and safe experience for every guest. We have equipped rooms, free Wi-Fi, personalized service, modern spaces and an excellent location in Tacna.",
            "¿Listo para disfrutar tu estadía?" => "Ready to enjoy your stay?",
            "Reserva hoy mismo y vive una experiencia inolvidable." => "Book today and enjoy an unforgettable experience.",
            "Tu hogar en Tacna, con atención cercana, habitaciones cómodas y ubicación estratégica." => "Your home in Tacna, with friendly service, comfortable rooms and a strategic location.",
            "Sobre Nosotros" => "About Us",
            "Conoce la historia de Madison Suite" => "Learn the story of Madison Suite",
            "Nuestra Historia" => "Our Story",
            "Madison Suite nació con el objetivo de brindar un lugar seguro, cómodo y moderno para todos nuestros huéspedes. Durante estos años hemos recibido visitantes nacionales e internacionales ofreciendo siempre una atención personalizada y habitaciones de excelente calidad." => "Madison Suite was created to offer a safe, comfortable and modern place for all our guests. Over the years we have welcomed national and international visitors, always providing personalized service and excellent-quality rooms.",
            "Misión" => "Mission",
            "Visión" => "Vision",
            "Brindar un servicio de hospedaje de alta calidad, garantizando comodidad, seguridad y una excelente atención para nuestros clientes." => "Provide high-quality lodging, ensuring comfort, safety and excellent service for our guests.",
            "Ser uno de los hoteles más reconocidos de Tacna, destacando por la calidad del servicio y la satisfacción de nuestros huéspedes." => "Become one of the most recognized hotels in Tacna, known for service quality and guest satisfaction.",
            "Nuestros Valores" => "Our Values",
            "Respeto" => "Respect",
            "Calidad" => "Quality",
            "Seguridad" => "Safety",
            "Compromiso" => "Commitment",
            "Tratamos a cada huésped con cordialidad." => "We treat every guest with kindness.",
            "Buscamos la excelencia en cada servicio." => "We seek excellence in every service.",
            "Protegemos a nuestros huéspedes las 24 horas." => "We protect our guests 24 hours a day.",
            "Trabajamos para superar las expectativas." => "We work to exceed expectations.",
            "NUESTROS SERVICIOS EXCLUSIVOS" => "OUR EXCLUSIVE SERVICES",
            "Disfruta de la comodidad y atención premium en Tacna." => "Enjoy comfort and premium service in Tacna.",
            "Servicios del Hotel" => "Hotel Services",
            "Servicios de Habitación" => "Room Services",
            "Restaurante" => "Restaurant",
            "Recepción" => "Reception",
            "Cochera" => "Parking",
            "Gratis" => "Free",
            "Incluido" => "Included",
            "Custodia de Equipaje" => "Luggage Storage",
            "Hidromasaje / Jacuzzi:" => "Whirlpool / Jacuzzi:",
            "Tina de hidromasaje privada en suites para un descanso profundo y relajante." => "Private whirlpool bathtub in suites for deep and relaxing rest.",
        ],
        "pt" => [
            "Nosotros" => "Sobre nós",
            "Servicios" => "Serviços",
            "Normas" => "Regras",
            "Galería" => "Galeria",
            "Reseñas" => "Avaliações",
            "Contacto" => "Contato",
            "Inicio" => "Início",
            "Habitaciones" => "Quartos",
            "Ubicación" => "Localização",
            "Elegancia y descanso" => "Elegância e descanso",
            "Encuentra el espacio perfecto para tu estadía en Tacna." => "Encontre o espaço perfeito para sua estadia em Tacna.",
            "Habitación Triple" => "Quarto Triplo",
            "Habitación Matrimonial" => "Quarto Matrimonial",
            "Habitación Doble" => "Quarto Duplo",
            "Habitación Familiar - 3p" => "Quarto Familiar - 3p",
            "Familiar Plus - 4p" => "Familiar Plus - 4p",
            "Suite Familiar - 3p" => "Suíte Familiar - 3p",
            "Suite Executive" => "Suíte Executiva",
            "1 cama doble" => "1 cama de casal",
            "1 cama matrimonial o 2 camas" => "1 cama matrimonial ou 2 camas",
            "1 cama doble extragrande" => "1 cama de casal extragrande",
            "1 cama individual y 1 cama doble" => "1 cama individual e 1 cama de casal",
            "2 camas individuales y 1 cama doble" => "2 camas individuais e 1 cama de casal",
            "Aire Acondicionado" => "Ar-condicionado",
            "Baño privado y TV cable" => "Banheiro privativo e TV a cabo",
            "Bañera de hidromasaje / Jacuzzi" => "Banheira de hidromassagem / Jacuzzi",
            "Escritorio de trabajo" => "Mesa de trabalho",
            "Sala de estar" => "Sala de estar",
            "Espacio amplio para familias" => "Espaço amplo para famílias",
            "Armario y artículos de baño" => "Armário e itens de banho",
            "Agua caliente" => "Água quente",
            "Vive una experiencia única con habitaciones cómodas, atención personalizada y el mejor servicio para hacer de tu estadía un momento inolvidable." => "Viva uma experiência única com quartos confortáveis, atendimento personalizado e o melhor serviço para tornar sua estadia inesquecível.",
            "Seguridad 24/7" => "Segurança 24/7",
            "Personal capacitado las 24 horas." => "Equipe treinada 24 horas por dia.",
            "Limpieza" => "Limpeza",
            "Habitaciones impecables." => "Quartos impecáveis.",
            "Confort" => "Conforto",
            "Ambientes modernos y acogedores." => "Ambientes modernos e acolhedores.",
            "7 años" => "7 anos",
            "Brindando la mejor experiencia." => "Oferecendo a melhor experiência.",
            "¿Por qué elegir Madison Suite?" => "Por que escolher Madison Suite?",
            "Nos enfocamos en ofrecer una experiencia cómoda y segura para cada huésped. Contamos con habitaciones equipadas, wifi gratuito, atención personalizada, ambientes modernos y una excelente ubicación en la ciudad de Tacna." => "Nos concentramos em oferecer uma experiência confortável e segura para cada hóspede. Temos quartos equipados, Wi-Fi gratuito, atendimento personalizado, ambientes modernos e uma excelente localização em Tacna.",
            "¿Listo para disfrutar tu estadía?" => "Pronto para aproveitar sua estadia?",
            "Reserva hoy mismo y vive una experiencia inolvidable." => "Reserve hoje mesmo e viva uma experiência inesquecível.",
            "Tu hogar en Tacna, con atención cercana, habitaciones cómodas y ubicación estratégica." => "Seu lar em Tacna, com atendimento próximo, quartos confortáveis e localização estratégica.",
            "Sobre Nosotros" => "Sobre nós",
            "Conoce la historia de Madison Suite" => "Conheça a história do Madison Suite",
            "Nuestra Historia" => "Nossa História",
            "Misión" => "Missão",
            "Visión" => "Visão",
            "Nuestros Valores" => "Nossos Valores",
            "Respeto" => "Respeito",
            "Calidad" => "Qualidade",
            "Seguridad" => "Segurança",
            "Compromiso" => "Compromisso",
            "Tratamos a cada huésped con cordialidad." => "Tratamos cada hóspede com cordialidade.",
            "Buscamos la excelencia en cada servicio." => "Buscamos excelência em cada serviço.",
            "Protegemos a nuestros huéspedes las 24 horas." => "Protegemos nossos hóspedes 24 horas por dia.",
            "Trabajamos para superar las expectativas." => "Trabalhamos para superar expectativas.",
            "NUESTROS SERVICIOS EXCLUSIVOS" => "NOSSOS SERVIÇOS EXCLUSIVOS",
            "Disfruta de la comodidad y atención premium en Tacna." => "Aproveite o conforto e o atendimento premium em Tacna.",
            "Servicios del Hotel" => "Serviços do Hotel",
            "Servicios de Habitación" => "Serviços de Quarto",
            "Restaurante" => "Restaurante",
            "Recepción" => "Recepção",
            "Cochera" => "Estacionamento",
            "Gratis" => "Grátis",
            "Incluido" => "Incluído",
            "Custodia de Equipaje" => "Guarda de Bagagem",
        ],
        "it" => [
            "Nosotros" => "Chi siamo",
            "Servicios" => "Servizi",
            "Normas" => "Regole",
            "Galería" => "Galleria",
            "Reseñas" => "Recensioni",
            "Contacto" => "Contatto",
            "Inicio" => "Home",
            "Habitaciones" => "Camere",
            "Ubicación" => "Posizione",
            "Elegancia y descanso" => "Eleganza e riposo",
            "Encuentra el espacio perfecto para tu estadía en Tacna." => "Trova lo spazio perfetto per il tuo soggiorno a Tacna.",
            "Habitación Triple" => "Camera Tripla",
            "Habitación Matrimonial" => "Camera Matrimoniale",
            "Habitación Doble" => "Camera Doppia",
            "Habitación Familiar - 3p" => "Camera Familiare - 3p",
            "Familiar Plus - 4p" => "Family Plus - 4p",
            "Suite Familiar - 3p" => "Suite Familiare - 3p",
            "Suite Executive" => "Suite Executive",
            "1 cama doble" => "1 letto matrimoniale",
            "1 cama matrimonial o 2 camas" => "1 letto matrimoniale o 2 letti",
            "1 cama doble extragrande" => "1 letto matrimoniale extra large",
            "1 cama individual y 1 cama doble" => "1 letto singolo e 1 matrimoniale",
            "2 camas individuales y 1 cama doble" => "2 letti singoli e 1 matrimoniale",
            "Aire Acondicionado" => "Aria condizionata",
            "Baño privado y TV cable" => "Bagno privato e TV via cavo",
            "Bañera de hidromasaje / Jacuzzi" => "Vasca idromassaggio / Jacuzzi",
            "Escritorio de trabajo" => "Scrivania",
            "Sala de estar" => "Zona soggiorno",
            "Espacio amplio para familias" => "Spazio ampio per famiglie",
            "Armario y artículos de baño" => "Armadio e articoli da bagno",
            "Agua caliente" => "Acqua calda",
            "Vive una experiencia única con habitaciones cómodas, atención personalizada y el mejor servicio para hacer de tu estadía un momento inolvidable." => "Vivi un'esperienza unica con camere confortevoli, attenzione personalizzata e il miglior servizio per rendere il tuo soggiorno indimenticabile.",
            "Seguridad 24/7" => "Sicurezza 24/7",
            "Personal capacitado las 24 horas." => "Personale qualificato 24 ore su 24.",
            "Limpieza" => "Pulizia",
            "Habitaciones impecables." => "Camere impeccabili.",
            "Confort" => "Comfort",
            "Ambientes modernos y acogedores." => "Ambienti moderni e accoglienti.",
            "7 años" => "7 anni",
            "Brindando la mejor experiencia." => "Offrendo la migliore esperienza.",
            "¿Por qué elegir Madison Suite?" => "Perché scegliere Madison Suite?",
            "¿Listo para disfrutar tu estadía?" => "Pronto a goderti il soggiorno?",
            "Reserva hoy mismo y vive una experiencia inolvidable." => "Prenota oggi stesso e vivi un'esperienza indimenticabile.",
            "Tu hogar en Tacna, con atención cercana, habitaciones cómodas y ubicación estratégica." => "La tua casa a Tacna, con servizio attento, camere confortevoli e posizione strategica.",
            "Sobre Nosotros" => "Chi siamo",
            "Conoce la historia de Madison Suite" => "Scopri la storia di Madison Suite",
            "Nuestra Historia" => "La Nostra Storia",
            "Misión" => "Missione",
            "Visión" => "Visione",
            "Nuestros Valores" => "I Nostri Valori",
            "Respeto" => "Rispetto",
            "Calidad" => "Qualità",
            "Seguridad" => "Sicurezza",
            "Compromiso" => "Impegno",
            "Tratamos a cada huésped con cordialidad." => "Trattiamo ogni ospite con cordialità.",
            "Buscamos la excelencia en cada servicio." => "Cerchiamo l'eccellenza in ogni servizio.",
            "Protegemos a nuestros huéspedes las 24 horas." => "Proteggiamo i nostri ospiti 24 ore su 24.",
            "Trabajamos para superar las expectativas." => "Lavoriamo per superare le aspettative.",
            "NUESTROS SERVICIOS EXCLUSIVOS" => "I NOSTRI SERVIZI ESCLUSIVI",
            "Disfruta de la comodidad y atención premium en Tacna." => "Goditi comfort e servizio premium a Tacna.",
            "Servicios del Hotel" => "Servizi dell'Hotel",
            "Servicios de Habitación" => "Servizi in Camera",
            "Restaurante" => "Ristorante",
            "Recepción" => "Reception",
            "Cochera" => "Parcheggio",
            "Gratis" => "Gratis",
            "Incluido" => "Incluso",
            "Custodia de Equipaje" => "Deposito Bagagli",
        ],
    ];

    return $maps[$lang] ?? [];
}

function normalizeTranslationText($text)
{
    $text = html_entity_decode($text, ENT_QUOTES | ENT_HTML5, "UTF-8");
    return preg_replace("/\s+/u", " ", trim($text));
}

function normalizedPublicTranslationMap($lang)
{
    $extraMap = [];
    $extraPath = __DIR__ . "/lang_extra.php";
    if (is_file($extraPath)) {
        $allExtraMaps = include $extraPath;
        $extraMap = is_array($allExtraMaps[$lang] ?? null) ? $allExtraMaps[$lang] : [];
    }

    $morePath = __DIR__ . "/lang_more.php";
    if (is_file($morePath)) {
        $allMoreMaps = include $morePath;
        if (is_array($allMoreMaps[$lang] ?? null)) {
            $extraMap = array_merge($extraMap, $allMoreMaps[$lang]);
        }
    }

    $rawMap = array_merge(publicTranslationMap($lang), publicTranslationOverrides($lang), $extraMap);
    $map = [];

    foreach ($rawMap as $key => $value) {
        $map[normalizeTranslationText(repairSpanishText($key))] = repairSpanishText($value);
    }

    return $map;
}

function publicTranslationFragments($lang)
{
    $maps = [
        "en" => [
            "Bienvenido," => "Welcome,",
            "comentario(s) registrados" => "registered comment(s)",
            "Desde aquí puedes revisar" => "From here you can review",
            "tus reservas, reclamos y datos personales." => "your bookings, complaints and personal data.",
            "Revisa tus reservas anteriores." => "Review your previous bookings.",
            "Ver reclamos" => "View complaints",
            "Ver perfil" => "View profile",
            "Cambiar Contraseña" => "Change Password",
            "Cambiar contraseña" => "Change password",
            "Actualiza tu contraseña de acceso." => "Update your access password.",
            "Ingresar" => "Sign in",
            "Registrarse" => "Sign up",
            "Regístrate" => "Sign up",
            "¿Olvidaste tu contraseña?" => "Forgot your password?",
            "¿Aún no tienes cuenta?" => "Don't have an account yet?",
            "¿Ya tienes una cuenta?" => "Already have an account?",
            "Volver al inicio de sesión" => "Back to sign in",
        ],
        "pt" => [
            "Bienvenido," => "Bem-vindo,",
            "comentario(s) registrados" => "comentário(s) registrado(s)",
            "Desde aquí puedes revisar" => "Aqui você pode revisar",
            "tus reservas, reclamos y datos personales." => "suas reservas, reclamações e dados pessoais.",
            "Revisa tus reservas anteriores." => "Revise suas reservas anteriores.",
            "Ver reclamos" => "Ver reclamações",
            "Ver perfil" => "Ver perfil",
            "Cambiar Contraseña" => "Alterar Senha",
            "Cambiar contraseña" => "Alterar senha",
            "Actualiza tu contraseña de acceso." => "Atualize sua senha de acesso.",
            "Ingresar" => "Entrar",
            "Registrarse" => "Cadastrar-se",
            "Regístrate" => "Cadastre-se",
            "¿Olvidaste tu contraseña?" => "Esqueceu sua senha?",
            "¿Aún no tienes cuenta?" => "Ainda não tem uma conta?",
            "¿Ya tienes una cuenta?" => "Já tem uma conta?",
            "Volver al inicio de sesión" => "Voltar ao login",
        ],
        "it" => [
            "Bienvenido," => "Benvenuto,",
            "comentario(s) registrados" => "commento/i registrato/i",
            "Desde aquí puedes revisar" => "Da qui puoi controllare",
            "tus reservas, reclamos y datos personales." => "le tue prenotazioni, i reclami e i dati personali.",
            "Revisa tus reservas anteriores." => "Controlla le tue prenotazioni precedenti.",
            "Ver reclamos" => "Vedi reclami",
            "Ver perfil" => "Vedi profilo",
            "Cambiar Contraseña" => "Cambia Password",
            "Cambiar contraseña" => "Cambia password",
            "Actualiza tu contraseña de acceso." => "Aggiorna la tua password di accesso.",
            "Ingresar" => "Accedi",
            "Registrarse" => "Registrati",
            "Regístrate" => "Registrati",
            "¿Olvidaste tu contraseña?" => "Hai dimenticato la password?",
            "¿Aún no tienes cuenta?" => "Non hai ancora un account?",
            "¿Ya tienes una cuenta?" => "Hai già un account?",
            "Volver al inicio de sesión" => "Torna al login",
        ],
    ];

    return $maps[$lang] ?? [];
}

function translateVisibleTextSegment($text, $map, $currentLang)
{
    $text = repairSpanishText($text);

    if ($currentLang === "es" || trim($text) === "") {
        return $text;
    }

    if (!preg_match("/^(\s*)(.*?)(\s*)$/su", $text, $matches)) {
        return $text;
    }

    $key = normalizeTranslationText($matches[2]);

    if (isset($map[$key])) {
        return $matches[1] . $map[$key] . $matches[3];
    }

    $translatedText = $text;
    foreach (publicTranslationFragments($currentLang) as $from => $to) {
        $translatedText = str_replace(repairSpanishText($from), repairSpanishText($to), $translatedText);
    }

    if ($translatedText !== $text) {
        return $translatedText;
    }

    return $text;
}

function translatePublicHtml($html)
{
    global $currentLang;

    if (strpos($_SERVER["SCRIPT_NAME"] ?? "", "/admin/") !== false) {
        return $html;
    }

    $map = normalizedPublicTranslationMap($currentLang);
    $parts = preg_split("/(<[^>]+>)/", $html, -1, PREG_SPLIT_DELIM_CAPTURE);

    foreach ($parts as $index => $part) {
        if ($part === "" || str_starts_with($part, "<")) {
            continue;
        }

        $parts[$index] = translateVisibleTextSegment($part, $map, $currentLang);
    }

    return implode("", $parts);
}

if (empty($GLOBALS["public_translation_buffer_started"]) && strpos($_SERVER["SCRIPT_NAME"] ?? "", "/admin/") === false) {
    $GLOBALS["public_translation_buffer_started"] = true;
    ob_start("translatePublicHtml");
}
?>
